### ISSUE TITLE
Synchronization Policy

### ISSUE THREAD

**Issue by nairvineet** [Tx3-Services/VERA-Configuration-Cookbook#19]
@amorris-tx3  am looking for a sampe Synchronization Policy.json file, which I couldnt find anywhere. Is it possible to share one?

**Comment by amorris-tx3** [comment]
Hi @nairvineet - Synchronization policies are integration-specific, and so we can probably publish an example if we know the integration type you're working on.  Is it a Tricentis Tosca integration or something else?

**Comment by nairvineet** [comment]
Thanks @amorris-tx3 for the respns . I am loking for integration with JIRA.

**Comment by amorris-tx3** [comment]
@nairvineet - Please see attached for a sample Synchronization Policy for integrating Jira w/ VERA DevOps.  Please note that you'll need to use the _Tx3 VERA Password Encryption Utility_ to encrypt the Jira service account password that will be used by VERA.  Please let me know if you don't have that utility already.

[Synchronization Policy.json.txt](https://github.com/Tx3-Services/VERA-Configuration-Cookbook/files/4940006/Synchronization.Policy.json.txt)

**Comment by nairvineet** [comment]
@amorris-tx3  - Thank you for the policy file. I don't have the utility with me. Could you please guide me to the location/ share if possible?

**Comment by amorris-tx3** [comment]
Hi @nairvineet - Yes, I can help you with this.  Please reach out to me directly at _amorris_ at _tx3services_ dot com.  Thanks!

**Comment by nairvineet** [comment]
@amorris-tx3  - Thanks a lot!
